import { useState } from 'react'
import { Card, Field, PageHeader, Pill, QueueTable, Row, Tabs, ToConfirm, VersionTag, type Column } from '../../components/ui'
import { modalities, type Modality } from '../../mock/program'

export default function ModalityConfig() {
  const [sel, setSel] = useState<Modality>(modalities[1])
  const [tab, setTab] = useState('identity')
  const columns: Column<Modality>[] = [
    { key: 'name', header: 'Modality', render: (r) => <><div className="font-semibold text-sand-900">{r.name}</div><div className="text-xs text-sand-500">{r.id} · {r.category}</div></> },
    { key: 'mode', header: 'Booking', render: (r) => <Pill tone={r.bookingMode === 'Book now' ? 'ok' : r.bookingMode === 'Request' ? 'warn' : 'neutral'} dot={false}>{r.bookingMode}</Pill> },
    { key: 'rules', header: 'Rules', render: (r) => <span className="text-xs text-sand-600">{r.duration} min · ≥{r.minSpacingDays} d apart · ≤{r.maxPerWeek}/wk</span> },
    { key: 'survey', header: 'Follow-up', render: (r) => r.surveyOffsets.length ? <span className="text-xs">{r.surveyTemplate} · +{r.surveyOffsets.join('/')} d</span> : <span className="text-xs text-sand-400">None</span> },
    { key: 'active', header: 'Status', render: (r) => <Pill tone={r.active ? 'ok' : 'neutral'}>{r.active ? 'Active' : 'Inactive'}</Pill> },
  ]
  return (
    <>
      <PageHeader eyebrow="Configuration · Program admin / physician" title="Modalities" description="One record per modality is the shared source for scheduling, surveys, patient instructions, consents and monitoring (requirements §9). Rooms and devices are separate resources." actions={<button className="btn-primary">+ Add modality</button>} />
      <div className="grid gap-5 xl:grid-cols-5">
        <div className="xl:col-span-2"><QueueTable rows={modalities} columns={columns} rowKey={(r) => r.id} rowTone={(r) => (r.active ? 'ok' : 'neutral')} onRowClick={setSel} /></div>
        <div className="xl:col-span-3">
          <Card title={<span className="flex items-center gap-2">{sel.name} <VersionTag>config v{sel.version}</VersionTag></span>} subtitle={`${sel.id} · ${sel.category} · owner ${sel.owner}`} actions={<div className="flex gap-2"><button className="btn-secondary px-3 py-1.5 text-xs">Audit history</button><button className="btn-primary px-3 py-1.5 text-xs">Save as v{sel.version + 1}</button></div>}>
            <Tabs value={tab} onChange={setTab} tabs={[{ key: 'identity', label: 'Identity' }, { key: 'poc', label: 'Plan of Care' }, { key: 'sched', label: 'Scheduling' }, { key: 'prep', label: 'Preparation' }, { key: 'survey', label: 'Survey follow-up' }, { key: 'alerts', label: 'Alert logic' }, { key: 'docs', label: 'Documents' }]} />
            {tab === 'identity' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Display name"><input className="input" defaultValue={sel.name} /></Field><Field label="Category"><input className="input" defaultValue={sel.category} /></Field><Field label="Location"><input className="input" defaultValue={sel.location} /></Field><Field label="eCW resource mapping"><input className="input" defaultValue={sel.ecwResource} /><div className="mt-1"><ToConfirm>whether rooms/devices exist as eCW resources</ToConfirm></div></Field><Field label="Active"><select className="input" defaultValue={sel.active ? 'Yes' : 'No'}><option>Yes</option><option>No</option></select></Field><Field label="Effective dates"><input className="input" defaultValue="Sep 1, 2026 → open" /></Field></div>}
            {tab === 'poc' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Physician authorization required"><select className="input" defaultValue={sel.authRequired ? 'Yes' : 'No'}><option>Yes</option><option>No</option></select></Field><Field label="Permitted stages"><input className="input" defaultValue={sel.stages.join(', ')} /></Field><Field label="Lead Actor applicability"><select className="input"><option>All</option><option>Specific Lead Actors…</option></select></Field><Field label="Start / stop conditions"><input className="input" defaultValue="Start: Plan of Care authorized · Stop: physician removes or program ends" /></Field><div className="sm:col-span-2"><Field label="Patient-specific limits"><input className="input" defaultValue="Allowed · physician may set max sessions per patient" /></Field></div></div>}
            {tab === 'sched' && <div className="grid gap-4 sm:grid-cols-3"><Field label="Duration (min)"><input className="input" defaultValue={sel.duration} /></Field><Field label="Buffer (min)"><input className="input" defaultValue={sel.buffer} /></Field><Field label="Booking mode"><select className="input" defaultValue={sel.bookingMode}><option>Book now</option><option>Request</option><option>Staff only</option></select></Field><Field label="Minimum spacing (days)"><input className="input" defaultValue={sel.minSpacingDays} /></Field><Field label="Max per week"><input className="input" defaultValue={sel.maxPerWeek} /></Field><Field label="Lead time (hours)"><input className="input" defaultValue={sel.leadTimeHours} /></Field><Field label="Cancellation window (hours)"><input className="input" defaultValue={sel.cancelWindowHours} /></Field><div className="sm:col-span-2"><Field label="Required resources (rooms, equipment, staff)"><div className="flex flex-wrap gap-1.5 pt-1">{sel.resources.map((r) => <Pill key={r} tone="teal" dot={false}>{r}</Pill>)}<button className="btn-ghost px-2 py-0.5 text-xs">+ add</button></div></Field></div><div className="sm:col-span-3 rounded-xl bg-sand-50 p-3 text-sm text-sand-600"><strong>Shown to patients as:</strong> “{sel.name}: {sel.duration} minutes. At least {sel.minSpacingDays} day{sel.minSpacingDays > 1 ? 's' : ''} between sessions, up to {sel.maxPerWeek} per week. Book at least {sel.leadTimeHours} hours ahead; cancel up to {sel.cancelWindowHours} hours before.”</div></div>}
            {tab === 'prep' && <div className="space-y-4"><Field label="Patient instructions"><textarea rows={3} className="input" defaultValue={sel.prep} /></Field><Field label="Prerequisites"><input className="input" defaultValue="Plan of Care authorized · consent signed" /></Field><Field label="Contraindication prompts (supplied by clinical leadership)"><textarea rows={2} className="input" defaultValue="Ask: pregnancy, pacemaker, open wounds. Placeholder — final list from Medical Director." /></Field><Field label="Required acknowledgements"><input className="input" defaultValue="“I have read the preparation instructions”" /></Field></div>}
            {tab === 'survey' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Follow-up survey required"><select className="input" defaultValue={sel.surveyOffsets.length ? 'Yes' : 'No'}><option>Yes</option><option>No</option></select></Field><Field label="Survey template"><select className="input" defaultValue={sel.surveyTemplate}><option>Post-treatment check-in v2</option><option>Laser follow-up v1</option><option>None</option></select></Field><Field label="Offsets after treatment (days)"><input className="input" defaultValue={sel.surveyOffsets.join(', ')} /></Field><Field label="Reminders"><input className="input" defaultValue="1 after 24 h · max 1" /></Field><Field label="Stop rule"><input className="input" defaultValue="Sequence complete · next session booked · patient paused" /></Field><Field label="Patient-initiated reporting"><select className="input"><option>Crash / flare report always available</option></select></Field></div>}
            {tab === 'alerts' && <div className="space-y-3 text-sm"><Row label="Rule set">{sel.alertRuleSet}</Row><Row label="Severity mapping">Program default (Informational → Emergency instruction)</Row><Row label="Recipients">Nursing (assigned) · treating physician for urgent</Row><Row label="Response target">Per level · see Alert rules</Row><Row label="After-hours">Queue + emergency language</Row><Row label="Emergency language"><VersionTag>Patient notice v1</VersionTag></Row><a href="#/staff/config/alerts" className="btn-secondary mt-2">Open alert rules</a></div>}
            {tab === 'docs' && <div className="space-y-3"><Row label="Required before first session">{sel.documents.join(', ') || 'None'}</Row><Row label="Re-sign when">Document version changes</Row><div className="mt-2"><ToConfirm>consent list and versions from Shibani</ToConfirm></div></div>}
          </Card>
        </div>
      </div>
    </>
  )
}
